// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Mayconrib808
package main

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

// Fixed bytes follow the independently pinned Rust wire format, including UTF-16
// euro characters. These are not generated by the Go encoder under test.
const goldenFrame = "010000000000c03f02000100000000400300000080bf0100000005005a006f006f002000ac20020000000200"

func TestPinnedUpstreamWire(t *testing.T) {
	b, _ := hex.DecodeString(goldenFrame)
	expected := frame{
		system: []floatEntry{{0, 1.5}}, variables: []floatEntry{{1, 2}, {3, -1}},
		strings: []stringEntry{{0, "Zoo €"}}, triggers: []uint16{0, 2},
	}
	f, err := readFrame(bytes.NewReader(b))
	if err != nil || !reflect.DeepEqual(f, expected) {
		t.Fatal(f, err)
	}
	for n := 0; n < len(b); n++ {
		if _, err := readFrame(bytes.NewReader(b[:n])); err == nil {
			t.Fatalf("accepted a truncated frame at byte %d", n)
		}
	}
	var output bytes.Buffer
	err = writeReply(&output, reply{
		system: []floatResult{{false, 99}}, variables: []floatResult{{true, 3}, {false, 99}},
		strings: []stringResult{{true, "ab"}}, triggers: []bool{true, false},
	})
	if err != nil || hex.EncodeToString(output.Bytes()) != "000000000001000040400000000000010200610062000100" {
		t.Fatal(hex.EncodeToString(output.Bytes()), err)
	}
}

type fakePlugin struct {
	starts, frames, finalizes, closes int
}

func (p *fakePlugin) start()            { p.starts++ }
func (p *fakePlugin) flags() byte       { return 15 }
func (p *fakePlugin) frame(frame) reply { p.frames++; return reply{} }
func (p *fakePlugin) finalize()         { p.finalizes++ }
func (p *fakePlugin) close()            { p.closes++ }

func TestHostLifecycleAndErrors(t *testing.T) {
	for _, test := range []struct {
		name                      string
		input                     []byte
		failure                   bool
		starts, finalizes, frames int
		output                    []byte
	}{
		{"normal", []byte{1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3}, false, 1, 1, 1, []byte{1, 15, 1}},
		{"EOF cleanup", []byte{1}, false, 1, 1, 0, []byte{1, 15}},
		{"duplicate START", []byte{1, 1}, true, 1, 1, 0, []byte{1, 15}},
		{"FRAME before START", []byte{2, 0, 0, 0, 0, 0, 0, 0, 0}, true, 0, 0, 0, nil},
		{"FINALIZE before START", []byte{3}, true, 0, 0, 0, nil},
		{"truncated frame", []byte{1, 2, 0}, true, 1, 1, 0, []byte{1, 15}},
		{"unknown opcode", []byte{1, 42}, true, 1, 1, 0, []byte{1, 15}},
	} {
		t.Run(test.name, func(t *testing.T) {
			p := &fakePlugin{}
			var output bytes.Buffer
			err := serve(bytes.NewReader(test.input), &output, func() (plugin, error) { return p, nil }, func() bool { return true })
			if (err != nil) != test.failure || p.starts != test.starts || p.finalizes != test.finalizes || p.frames != test.frames {
				t.Fatal(p, err)
			}
			if !bytes.Equal(output.Bytes(), test.output) || (p.starts > 0 && p.closes != 1) {
				t.Fatal(output.Bytes(), p)
			}
		})
	}
	var output bytes.Buffer
	err := serve(bytes.NewReader([]byte{1}), &output, func() (plugin, error) { return nil, fmt.Errorf("missing DLL") }, func() bool { return true })
	if err == nil || !bytes.Equal(output.Bytes(), []byte{0, 0}) {
		t.Fatal("failed-load handshake", output.Bytes(), err)
	}
}

func TestMessagePumpRunsWhileInputIsIdle(t *testing.T) {
	reader, writer := io.Pipe()
	defer reader.Close()
	defer writer.Close()
	var count atomic.Int32
	done := make(chan error, 1)
	go func() {
		done <- serve(reader, io.Discard, func() (plugin, error) { return &fakePlugin{}, nil }, func() bool { return count.Add(1) < 3 })
	}()
	select {
	case err := <-done:
		if err != nil || count.Load() < 3 {
			t.Fatal(count.Load(), err)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("message pump blocked on stdin")
	}
}

func TestPluginSelectionAndPlacement(t *testing.T) {
	root := filepath.Join(t.TempDir(), "OMSI teste ç")
	dir := filepath.Join(root, "Plugins", "sub")
	if err := os.MkdirAll(dir, 0755); err != nil {
		t.Fatal(err)
	}
	dll := filepath.Join(dir, "bbs.dll")
	exe := filepath.Join(root, "OpenOMSI_BCS_PluginHost32.exe")
	for _, path := range []string{dll, exe, filepath.Join(root, "Omsi.exe")} {
		if err := os.WriteFile(path, []byte("test fixture"), 0644); err != nil {
			t.Fatal(err)
		}
	}
	canonicalRoot, err := filepath.EvalSymlinks(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, got, err := pluginPaths(dll, exe); err != nil || !strings.EqualFold(got, canonicalRoot) {
		t.Fatal(got, err)
	}
	for _, pair := range [][2]string{
		{filepath.Join(dir, "another.dll"), exe},
		{dll, filepath.Join(root, "Omsi.exe") + ".missing"},
		{dll, filepath.Join(dir, "bbs.dll")},
	} {
		if _, _, err := pluginPaths(pair[0], pair[1]); err == nil {
			t.Fatal("accepted invalid plugin/deployment", pair)
		}
	}
	if err := os.Remove(filepath.Join(root, "Omsi.exe")); err != nil {
		t.Fatal(err)
	}
	if _, _, err := pluginPaths(dll, exe); err == nil {
		t.Fatal("accepted missing original OMSI root")
	}
}
